Network setup, initial hello set

diff --git a/custom-scripts/S41network-config b/custom-scripts/S41network-config
--- a/custom-scripts/S41network-config
+++ b/custom-scripts/S41network-config
@@ -3,28 +3,32 @@
 # Configuring host communication.
 #
 
+IP_OF_HOST="172.29.251.101"
+
 case "$1" in
   start)
-	printf "Configuring host communication."
-	
-	/sbin/ifconfig eth0 192.168.1.10 up
-	/sbin/route add -host 172.16.5.4 dev eth0
-	/sbin/route add default gw 172.16.5.4
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
-	;;
+    printf "Configuring host communication."
+    
+    /sbin/ifconfig eth0 192.168.1.10 up
+    /sbin/route add -host $IP_OF_HOST dev eth0
+    /sbin/route add default gw $IP_OF_HOST
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    ;;
   stop)
-	printf "Shutdown host communication. "
-	/sbin/route del default
-	/sbin/ifdown -a
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
-	;;
+    printf "Shutdown host communication. "
+    /sbin/route del default
+    /sbin/ifdown -a
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    ;;
   restart|reload)
-	"$0" stop
-	"$0" start
-	;;
+    "$0" stop
+    "$0" start
+    ;;
   *)
-	echo "Usage: $0 {start|stop|restart}"
-	exit 1
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
 esac
 
 exit $?
+
+
